version: '3'
services:
  web:
    build: site
    ports :
     - "8080:80"
    volumes:
     - ./www:/var/www/html/
     - ./server/000-default.conf:/etc/apache2/sites-available/000-default.conf
     - ./server/apache2.conf:/etc/apache2/apache2.conf
     - ./server/php.ini:/usr/local/etc/php/php.ini

  db:
    image: postgres
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: Portfolio_DB
      POSTGRES_USER: Portfolio_USER
      POSTGRES_PASSWORD: Portfolio
