/:
  controller: Main
  action: home

/a-propos:
  controller: Main
  action: aboutUs

/login:
  controller: Security
  action: login

/logout:
  controller: Security
  action: logout

/register:
  controller: Security
  action: register

/forgot-password:
  controller: Security
  action: pwdForget

/account:
  controller: Security
  action: modifieAccount

/email-verification:
  controller: Security
  action: verifyEmailNotify

/password-verification-notify:
  controller: Security
  action: ChangePasswordNotify

/verify2:
  controller: Security
  action: ChangePasswordVerification

/verify:
  controller: Security
  action: verifyEmail

/email-confirmed:
  controller: Security
  action: confirmedEmail

/needtologout:
  controller: Security
  action: needToLogout

/password-changed:
  controller: Security
  action: passwordChangedSucces

/installer1-3:
  controller: Installer
  action: installBdd

/installer2-3:
  controller: Installer
  action: installAdminAccount

/installer3-3:
  controller: Installer
  action: installSite

/dashboard:
  controller: Main
  action: dashboard
  
/hard-delete:
  controller: Security
  action: hardDeleteAccount

/soft-delete:
  controller: Security
  action: softDeleteAccount

/account-modified-notify:
  controller: Security
  action: accountModifiedNotify
