
# MAIN ----------------------------------------------------------------------------------------

/:
  controller: Main
  action: home

/a-propos:
  controller: Main
  action: aboutUs

/login:
  controller: Security
  action: login

/register:
  controller: Security
  action: register

/account:
  controller: Security
  action: modifieAccount

/dashboard:
  controller: Main
  action: dashboard

/contact:
  controller: Main
  action: contact


# SECURITY ------------------------------------------------------------------------------------

/logout:
  controller: Security
  action: logout

/forgot-password:
  controller: Security
  action: pwdForget

/verify2:
  controller: Security
  action: ChangePasswordVerification

/verify:
  controller: Security
  action: verifyEmail

/email-confirmed:
  controller: Security
  action: confirmedEmail

/needtologout:
  controller: Security
  action: needToLogout

/password-changed:
  controller: Security
  action: passwordChangedSucces

/delete-account:
  controller: Security
  action: DeleteAccount

/installer:
  controller: Installer
  action: installer


# COMMENTS ---------------------------------------------------------------------------------------

/dashboard/comments:
  controller: Admin
  action: comments

/commentUpdate/{pages}:
  path: /pages/{pages}
  controller: Admin
  action: commentsUpdate

/commentDelete/{pages}:
  path: /pages/{pages}
  controller: Admin
  action: commentsDelete


# PAGE ---------------------------------------------------------------------------------------

/dashboard/pages:
  controller: Page
  action: showAllPages

/dashboard/pages/createPage:
  controller: Page
  action: createPage

/dashboard/pages/editPage:
  controller: Page
  action: editPage

/page/{pageId}:
    controller: Page
    action: showPage



# ARTICLES ---------------------------------------------------------------------------------------

/dashboard/articles:
  controller: Article
  action: showAllArticles

/dashboard/articles/createArticle:
  controller: Article
  action: createArticle

/dashboard/articles/editArticle:
  controller: Article
  action: editArticle

/article/{articleId}:
    controller: Article
    action: showArticle


# USERS ---------------------------------------------------------------------------------------

/dashboard/users:
  controller: User
  action: showAllUsers

/dashboard/users/createUser:
  controller: User
  action: createUser

/dashboard/users/deleteUser/{userId}:
  controller: User
  action: deleteUser

/dashboard/users/confirmDeleteUser/{userId}:
  controller: User
  action: confirmDeleteUser

/dashboard/users/editUser/{userId}:
  controller: User
  action: editUser





