
# MAIN ----------------------------------------------------------------------------------------

/:
  controller: Main
  action: home

/a-propos:
  controller: Main
  action: aboutUs

/login:
  controller: Security
  action: login

/register:
  controller: Security
  action: register

/account:
  controller: Security
  action: modifieAccount

/dashboard:
  controller: Main
  action: dashboard

/contact:
  controller: Main
  action: contact


# SECURITY ------------------------------------------------------------------------------------

/logout:
  controller: Security
  action: logout

/forgot-password:
  controller: Security
  action: pwdForget

/verify2:
  controller: Security
  action: ChangePasswordVerification

/verify:
  controller: Security
  action: verifyEmail

/email-confirmed:
  controller: Security
  action: confirmedEmail

/needtologout:
  controller: Security
  action: needToLogout

/password-changed:
  controller: Security
  action: passwordChangedSucces

/delete-account:
  controller: Security
  action: DeleteAccount

/installer:
  controller: Installer
  action: installer


# ADMIN ---------------------------------------------------------------------------------------

/dashboard/comments:
  controller: Admin
  action: comments

/commentUpdate/{id}:
  controller: Admin
  action: commentsUpdate

/commentDelete/{id}:
  controller: Admin
  action: commentsDelete



# MENU ---------------------------------------------------------------------------------------

/dashboard/menus:
  controller: Admin
  action: menus

/dashboard/menus/create:
  controller: Admin
  action: menusCreate
# PAGE ---------------------------------------------------------------------------------------

/dashboard/pages:
  controller: Admin
  action: pagesShowAdmin

/dashboard/pages/create:
  controller: Admin
  action: createPages

/editPage/{id}:
  controller: Admin
  action: editPages

/deletePage/{id}:
  controller: Admin
  action: deletePages

/page/{id}:
    controller: Pages
    action: show

/menu/{id}:
  controller: Menus
  action: show

/editMenu/{id}:
  controller: Admin
  action: menuUpdate

/deleteMenu/{id}:
  controller: Admin
  action: menuDelete



# USERS ---------------------------------------------------------------------------------------

/dashboard/users:
  controller: Admin
  action: users

/dashboard/users/create:
  controller: Admin
  action: createUsers

/userUpdate/{id}:
  controller: Admin
  action: userUpdate

/userDelete/{id}:
  controller: Admin
  action: userDelete

/dashboard/template:
  controller: Admin
  action: showTemplate

/template/create:
  controller: Admin
  action: createTemplate

/GetTemplates:
  controller: Templates
  action: SetTemplates

/deleteTemplate/{id}:
  controller: Admin
  action: deleteTPL

/editTemplate/{id}:
  controller: Admin
  action: editTPL

/setTemplate/{id}:
  controller: Admin
  action: setTemplate
