
# MAIN ----------------------------------------------------------------------------------------

/:
  controller: Main
  action: home

/a-propos:
  controller: Main
  action: aboutUs

/login:
  controller: Security
  action: login

/register:
  controller: Security
  action: register

/account:
  controller: Security
  action: modifieAccount

/dashboard:
  controller: Main
  action: dashboard


# SECURITY ------------------------------------------------------------------------------------

/logout:
  controller: Security
  action: logout

/forgot-password:
  controller: Security
  action: pwdForget

/verify2:
  controller: Security
  action: ChangePasswordVerification

/verify:
  controller: Security
  action: verifyEmail

/email-confirmed:
  controller: Security
  action: confirmedEmail

/needtologout:
  controller: Security
  action: needToLogout

/password-changed:
  controller: Security
  action: passwordChangedSucces

/delete-account:
  controller: Security
  action: DeleteAccount

/installer:
  controller: Installer
  action: installer


# ADMIN ---------------------------------------------------------------------------------------

/dashboard/users:
  controller: Admin
  action: users

/dashboard/comments:
  controller: Admin
  action: comments

# MENU ---------------------------------------------------------------------------------------

/dashboard/menus:
  controller: Menu
  action: menus

# PAGE ---------------------------------------------------------------------------------------

/dashboard/pages:
  controller: Pages
  action: pages

/dashboard/pages/create:
  controller: Pages
  action: create

/article/{pages}:
    path: /article/{articleId}
    controller: Pages
    action: show