/:
  controller: Main
  action: home

/a-propos:
  controller: Main
  action: aboutUs

/login:
  controller: Security
  action: login

/logout:
  controller: Security
  action: logout

/register:
  controller: Security
  action: register

/forgot-password:
  controller: Security
  action: pwdForget

/account:
  controller: Security
  action: modifieAccount

/verify2:
  controller: Security
  action: ChangePasswordVerification

/verify:
  controller: Security
  action: verifyEmail

/email-confirmed:
  controller: Security
  action: confirmedEmail

/needtologout:
  controller: Security
  action: needToLogout

/password-changed:
  controller: Security
  action: passwordChangedSucces

/installer:
  controller: Installer
  action: installer

/dashboard:
  controller: Main
  action: dashboard
  
/delete-account:
  controller: Security
  action: DeleteAccount